Add controllers
Aleksey01091993/java-shareit pull request #1
Opened 2023-12-16 09:36 UTC by Aleksey01091993

2023-12-17 14:09 UTC, YazykovMikhail requested changes

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  /**
Удаляй комментарии, в реалихованных классах. 
Этот коммеетрий значит что нужно сделать, ты уже сделал

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDTO create(@RequestBody Item item, @RequestHeader("X-Sharer-User-Id") Long userId) throws Exception {
Модуль не должна приодить в контроллер, для этого есть dto обьекты.
Сделай dto для ответа назови ItemResponseDto
а для запросов обычно для каждого запроса свое dto, потому что в каждом запросе необходимы свои поля.
нарпимер 
ItemCreateRequestDto
ItemUpdateRequestDto

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +public interface ItemStorage extends JpaRepository<Item, Long> {
Вообще в задании сказано:
В качестве DAO создайте реализации, которые будут хранить данные в памяти приложения. Работу с базой данных вы реализуете в следующем спринте.

Ну раз сделал с бд тут, ок, пусть будет

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        if (item.getAvailable() == null || item.getDescription() == null || item.getName() == null
что бы не делать такую проверку, в контролелре нужно поставить аннотацию @Valid 
а в dto на поля накинуть соотвествующие аннотации для проверки
@NotBlank и так далее

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                @RequestParam(required = false) String text) {
как будто бы text тут не нужен

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        if (search.isEmpty()) {
если search == null будет NPE
search == null || search.isEmpty()
так будет получше

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public ItemDTO get(Long itemId) throws Exception {
не надо пробрасывать исключение, ткм более тут его нет

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public ItemDTO update(Item item, Long userId, Long itemId) throws Exception {
не надо пробрасывать исключение, просто исключение которые ты сделал сам, наследуй от RuntimeException

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +                throw new NotFound404("not found");
наследуй свои исключения RuntimeException
и цифры в названии класса писать не очень. 
просто NotFoundException

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/exception/NotFound404.java
> +public class NotFound404 extends Exception {
наследуй от RuntimeException

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/exception/BadRequest400.java
> +public class BadRequest400 extends RuntimeException {
наследуй от RuntimeException
что бы не было необходимости обязательно обрабаыать/прокидывать, обрабаыать можно когда что то можно сделать, тут сделать ничего нельзя обьект не найден, точка.

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public ItemDTO update(Item item, Long userId, Long itemId) throws Exception {
Убери везде

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +            user = userStorage.findById(userId).get();
лучше вот так:
```
   User user = userStorage.findById(userId)
                .orElseThrow(() -> new NotFound404("user not found by id: " + userId));
```

поправь везде

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +            user = userStorage.findById(userId).get();
соответсвенно  try { будет не нужен

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public List<User> getAll() {
в контроллере используются только dto, потом в сервисе из dto в model и уже репозиторий рабоатет с моделью

2023-12-17 14:09 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @NotNull
соответсвенно эти аннотации не нужно в модели, потому что они не используются на руовне контроллера.

2023-12-20 05:23 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  /**
выполнено

2023-12-20 07:16 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +public interface ItemStorage extends JpaRepository<Item, Long> {
+

2023-12-20 07:16 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        if (item.getAvailable() == null || item.getDescription() == null || item.getName() == null
+

2023-12-20 07:17 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                @RequestParam(required = false) String text) {
исправил на search

2023-12-20 07:27 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        if (search.isEmpty()) {
+

2023-12-20 07:29 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public ItemDTO get(Long itemId) throws Exception {
есть если пользователь не найден то выскачет нот фоунд 404

2023-12-20 07:32 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public ItemDTO get(Long itemId) throws Exception {
+

2023-12-20 07:32 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public ItemDTO update(Item item, Long userId, Long itemId) throws Exception {
+

2023-12-20 07:35 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +                throw new NotFound404("not found");
унаследовал по поводу цифр наоборот очень удобно сразу понятно какую ошубку ты хочеш выдать в ответ

2023-12-20 07:35 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/exception/NotFound404.java
> +public class NotFound404 extends Exception {
+

2023-12-20 07:36 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/exception/BadRequest400.java
> +public class BadRequest400 extends RuntimeException {
+

2023-12-20 07:36 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +            user = userStorage.findById(userId).get();
+

2023-12-20 08:11 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @NotNull
+

2023-12-20 08:12 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public List<User> getAll() {
+

2023-12-20 08:12 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDTO create(@RequestBody Item item, @RequestHeader("X-Sharer-User-Id") Long userId) throws Exception {
+

2023-12-20 08:19 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public List<User> getAll() {
тут не совсем понятно насколько я читал про дто: мы в базу сохроняем полноценную модель а потом уже из базы конвертируем ее для наших нужд(ответов) так как нам нужно потому я пощитал что дто будет наследоватся от юзера что даст возможность возврощать обьекты дто а контроллер будет их конвектировать и выдовать нужный результат это позволит в дальнейшем существенно сократить написания кода потому что нам не нежно будет повторно писать одни и те же методы в сервисе и контролере а даст возможность их переиспользовать

2023-12-20 15:57 UTC, YazykovMikhail commented
комиты с описанием:
@Aleksey01091993
[все зделанно](https://github.com/Aleksey01091993/java-shareit/pull/1/commits/0c1a040092c158589af107c92fded9986e2f20c6)

это не очень) в сообщении стоит писать что конкретно было сделано/поправлено

2023-12-24 04:21 UTC, merged