Add bookings
Aleksey01091993/java-shareit pull request #2
Opened 2024-01-02 12:44 UTC by Aleksey01091993

2024-01-06 10:24 UTC, YazykovMikhail commented
Обрати внимание, что у тебя не собрался билд. Нужно разобраться и поправить

2024-01-06 10:44 UTC, YazykovMikhail requested changes

2024-01-06 10:44 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestBody @Valid @Nullable BookingResponseDTO bookingResponseDTO,
У тебя в запрос приходит  BookingResponseDTO - как о не очень, в плане названия, BookingRequestDto
А как раз ответ назвать BookingResponseDto

2024-01-06 10:44 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingController(
если в переносе строк нет необходимости, не делай их
public BookingController(@Autowired BookingService service) {
        this.service = service;
    }

2024-01-06 10:44 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        return booking;
return newBooking;
Стоит возвращать то что было насамом деле сохранено

2024-01-06 10:44 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    public Booking approved(Long bookingId, Long userId, Boolean approved) {
чуть по структуре, вот так будет получше:

```
public Booking approved(Long bookingId, Long userId, Boolean approved) {
        Booking newBooking = bookingStorage.findById(bookingId)
                .orElseThrow(() -> new NotFound404("booking not found by id: " + bookingId));
        userStorage.findById(userId)
                .orElseThrow(() -> new NotFound404("owner not found by id:" + userId));
        if (!newBooking.getItem().getOwner().getId().equals(userId)) {
            throw new NotFound404("owner not found by id:" + userId);
           
        }
        if (newBooking.getStatus() != WAITING) {
            throw new BadRequest400("status error");
        }
        if (approved) {
            newBooking.setStatus(APPROVED);
        } else {
            newBooking.setStatus(REJECTED);
        }
        return bookingStorage.save(newBooking);
    }
```

2024-01-06 10:44 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/exception/InternalServerError500.java
> +public class InternalServerError500 extends RuntimeException{
RuntimeException { - пробел
Название исключения не очень, назови тогда как нибудь
BusinessServiceException

2024-01-06 10:44 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/exception/InternalServerError500.java
> +public class InternalServerError500 extends RuntimeException{
В других исключениях где есть цифры тоже их убери. К примеру 
NotFound404 -> NotFoundException
BadRequest400 -> BadRequestException

2024-01-06 10:44 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDTO itemUpdateDTO(@RequestBody @Nullable ItemResponseDTO item,
Так же
ItemResponseDto - это ответ
ItemRequestDto - это запрос
Так же могут быть (и обвчно бывают) dto для каждого эндпоинта, если это нужно, например
ItemCreateRequestDto
ItemUpdateRequestDto
потому что поля в них бывают разные и для каждого эндпоинта нужны только те поля которые там используются. - это на будущее

2024-01-06 10:44 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        Item itemOne = itemStorage.save(ItemMapper.toItem(null, item, null, null, user, null));
itemOne - не очень название для перемеенно. Название должно нести смысл, а не просто для того что бы было. 
или itemSaved 
или оно вообще тут не нужно
return itemStorage.save(ItemMapper.toItem(null, item, null, null, user, null));

2024-01-06 10:44 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public Item update(ItemResponseDTO item, Long userId, Long itemId) {
Вот эти проверки не нужны:
```
if (item.getName() != null) {
            itemNew.setName(item.getName());
        }
        if (item.getAvailable() != null) {
            itemNew.setAvailable(item.getAvailable());
        }
        if (item.getDescription() != null) {
            itemNew.setDescription(item.getDescription());
        }
```
потому что в dto они уже проверяются с помошью аннотаций 
сделай маппер и вынеси это в мапер:
```
itemNew.setName(item.getName());
        itemNew.setAvailable(item.getAvailable());
        itemNew.setDescription(item.getDescription());
```

2024-01-09 06:49 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingController(
+

2024-01-09 06:51 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestBody @Valid @Nullable BookingResponseDTO bookingResponseDTO,
+

2024-01-09 06:54 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        return booking;
+

2024-01-09 07:04 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    public Booking approved(Long bookingId, Long userId, Boolean approved) {
+

2024-01-09 07:06 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/exception/InternalServerError500.java
> +public class InternalServerError500 extends RuntimeException{
+

2024-01-09 07:08 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDTO itemUpdateDTO(@RequestBody @Nullable ItemResponseDTO item,
+

2024-01-09 08:14 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        Item itemOne = itemStorage.save(ItemMapper.toItem(null, item, null, null, user, null));
+

2024-01-09 10:11 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public Item update(ItemResponseDTO item, Long userId, Long itemId) {
+

2024-01-10 07:25 UTC, YazykovMikhail approved these changes

2024-01-10 09:32 UTC, merged