Add item requests
Aleksey01091993/java-shareit pull request #3
Opened 2024-01-18 16:03 UTC by Aleksey01091993

2024-01-19 14:46 UTC, YazykovMikhail requested changes

2024-01-19 14:46 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>              ) {
везде разная разметка, если делаешь переносы, то сделай разметку такую же как у тебя в самом первом эдпоинте 
вот в этом createBookingDTO

2024-01-19 14:46 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (from != null && size != null) {
лучше логировать все что пришло, а уже логику разделения на методы вынести в сервис, это все таки бизнес логика.

2024-01-19 14:46 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    List<ItemRequestToItem> items;
модификатор доступа

2024-01-19 14:46 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    List<ItemRequestToItem> items;
как будто это поле не нужно, оно используется только в маппере и все. 
Да и в целом не нужно

2024-01-19 14:46 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/request/model/ItemRequestToItem.java
> +public class ItemRequestToItem {
Как будто этот класс не нужен

2024-01-19 14:46 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +
лишние отступы убирай

2024-01-21 07:24 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>              ) {
+

2024-01-21 07:58 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (from != null && size != null) {
+

2024-01-21 07:58 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    List<ItemRequestToItem> items;
+

2024-01-21 08:01 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    List<ItemRequestToItem> items;
+

2024-01-21 08:12 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/request/model/ItemRequestToItem.java
> +public class ItemRequestToItem {
Этот класс нужен

2024-01-21 08:15 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    List<ItemRequestToItem> items;
если его убрать вся логика дто рушится

2024-01-21 08:16 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    List<ItemRequestToItem> items;
он нужен для правильного возвращения данных

2024-01-21 08:17 UTC, Aleksey01091993 commented on src/main/java/ru/practicum/shareit/request/model/ItemRequestToItem.java
> +public class ItemRequestToItem {
он нужен для правильного возвращения данных

2024-01-21 20:45 UTC, merged