Add docker
Aleksey01091993/java-shareit pull request #4
Opened 2024-02-09 19:09 UTC by Aleksey01091993

2024-02-10 13:56 UTC, YazykovMikhail requested changes

2024-02-10 13:56 UTC, YazykovMikhail commented on shareIt-gateway/src/main/java/ru/practicum/user/UserController.java
> +    public ResponseEntity<Object> userCreateDTO
В названиях методов не нужно писать про dto, название метода должно отражать смысл, а не какой тип он возвращает
Убери везде

2024-02-10 13:56 UTC, YazykovMikhail commented on shareIt-server/src/main/java/ru/practicum/item/service/ItemService.java
> +        return new ResponseEntity<>(ItemMapper.toItemDTO(newItem, newItem.getComments()), HttpStatus.OK);
обычно из сервиса возвощается дто, а уже в контроллере оборачивают ответ сервиса в 
new ResponseEntity<>

как то вот так:
```
Контроллер {

  @Get
  method() {
    log.info
    Dto response = service.method();
    log.info
    return ResponseEntity.ok(response)
  }

}
```

2024-02-10 13:57 UTC, YazykovMikhail reviewed
Так же обрати внимание что тесты не прошли, нужно поправить

2024-02-10 16:47 UTC, Aleksey01091993 commented on shareIt-gateway/src/main/java/ru/practicum/user/UserController.java
> +    public ResponseEntity<Object> userCreateDTO
+

2024-02-12 11:55 UTC, Aleksey01091993 commented on shareIt-server/src/main/java/ru/practicum/item/service/ItemService.java
> +        return new ResponseEntity<>(ItemMapper.toItemDTO(newItem, newItem.getComments()), HttpStatus.OK);
+

2024-02-12 14:20 UTC, YazykovMikhail approved these changes

2024-03-18 15:46 UTC, merged